# starship config for thyme
# https://github.com/chenhao-ye/thyme

# format='''[\[$username($hostname)\]](white) $directory ([\[$git_branch(:$git_commit)(:$git_status)(:$git_state)\]](yellow))$line_break$character$docker_context'''

add_newline = true

format = '''$directory ([\[$git_branch(:$git_commit)(:$git_status)(:$git_state)\]](yellow))$fill$golang$python$nodejs$rust$java$ruby$php$javascript$typescript$c$cpp$csharp$kotlin$swift$scala$haskell$elixir$dart$line_break$character'''
right_format = '''($jobs)($status)($cmd_duration)$time'''

[fill]
symbol = ' '

# [username]
# format = '[$user](blue)'
# show_always = true

# [hostname]
# format = '[@$hostname](cyan)'

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vicmd_symbol = '[❮](bold blue)'

[directory]
format = '[$path]($style)[$read_only]($read_only_style)'
style = 'green'
truncation_length = 1
truncate_to_repo = false
truncation_symbol = './'

[git_branch]
format = '[$branch](yellow)'

[git_commit]
format = '[$hash](yellow)'

[git_status]
format = '[$all_status$ahead_behind](yellow)'

[git_state]
format = '[$state($progress_current/$progress_total)](yellow)'

[line_break]
disabled = false

[time]
format = '[$time](green)'
time_format = '  %I:%M %p'
use_12hr = true
disabled = true

[cmd_duration]
format = '[\[$duration\]](yellow)'
min_time = 1
show_milliseconds = true
disabled = false

[status]
format = '[\[$status(:$common_meaning)(:$signal_name)\]](red)'
disabled = false

[jobs]
format = '[\[$symbol(:$number)\]](cyan)'
symbol = '⚙'
symbol_threshold = 1
number_threshold = 2


# langages

[golang]
format = '[go $version](bold cyan) '

[python]
format = '[py $version](bold yellow) '

[nodejs]
format = '[njs $version](bold green) '

[rust]
format = '[rs $version](bold red) '

[java]
format = '[java $version](bold blue) '

[ruby]
format = '[rb $version](bold magenta) '

[php]
format = '[php $version](bold purple) '

[c]
format = '[c $version](bold blue) '

[kotlin]
format = '[kt $version](bold orange) '

[swift]
format = '[swift $version](bold red) '

[scala]
format = '[scala $version](bold red) '

[haskell]
format = '[hs $version](bold purple) '

[elixir]
format = '[ex $version](bold purple) '

[dart]
format = '[dart $version](bold blue) '

